from pydantic import BaseModel, Field, ConfigDict
from typing import Optional

# --- Request Models (Input) ---
class ScanRequest(BaseModel):
    """
    Represents the input payload required to initiate a supply chain risk scan.

    This model validates the JSON body sent to the POST /api/scan endpoint.

    Attributes:
        region (str): The target geographic location to monitor (e.g., "Taiwan", "Shenzhen").
                      This string is passed directly to the Watchtower Agent.
        user_id (Optional[str]): An identifier for the user initiating the request.
                                 Defaults to 'demo-user' for stateless demo purposes.
    """
    region: str = Field(..., description="Target region to scan", example="Taiwan")
    user_id: Optional[str] = Field("demo-user", description="ID of the requesting user")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "region": "Taiwan",
                "user_id": "admin_01"
            }
        }
    )

class PurchaseRequest(BaseModel):
    """
    Represents the input payload required to trigger a procurement action.

    This model validates the JSON body sent to the POST /api/purchase endpoint.

    Attributes:
        part_name (str): The SKU or name of the component to purchase.
        quantity (int): The number of units to order.
        risk_level (str): The urgency level (e.g., "CRITICAL"). 
                          If "CRITICAL", the agent will mark the order as urgent.
    """
    part_name: str = Field(..., description="The SKU or name of the component", example="Logic-Core-CPU-X1")
    quantity: int = Field(..., gt=0, description="Quantity to purchase")
    risk_level: str = Field("CRITICAL", description="Risk level determines shipment urgency")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "part_name": "Logic-Core-CPU-X1",
                "quantity": 50,
                "risk_level": "CRITICAL"
            }
        }
    )

# --- Response Models (Output) ---

class ScanResponse(BaseModel):
    """
    Represents the standardized output returned to the client after a scan completes.

    Attributes:
        region (str): The geographic location that was analyzed.
        risk_level (str): A categorical classification of the risk (e.g., "CRITICAL", "LOW").
        summary (str): The detailed natural language report generated by the Watchtower Agent.
        timestamp (str): The ISO 8601 formatted date and time when the scan was completed.
    """
    region: str
    risk_level: str
    summary: str
    timestamp: str

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "region": "Taiwan",
                "risk_level": "CRITICAL",
                "summary": "**RISK ALERT**: Earthquake detected. Logic-Core-CPUs are at critical low stock.",
                "timestamp": "2025-11-30T14:35:43.598235"
            }
        }
    )

class PurchaseResponse(BaseModel):
    """
    Represents the standardized output returned after a purchase attempt.

    Attributes:
        status (str): The outcome of the transaction (e.g., "COMPLETED", "FAILED", "PAUSED_FOR_APPROVAL").
        summary (str): The detailed natural language report from the Procurement Agent.
        timestamp (str): The ISO 8601 formatted date and time when the operation finished.
    """
    status: str
    summary: str
    timestamp: str

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "status": "COMPLETED",
                "summary": "Order confirmed. Order ID: PO-12345.",
                "timestamp": "2025-11-30T14:40:00.000000"
            }
        }
    )